##########
# collectionbuilder-sheets
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-sheets
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-sheets

##########
# SITE SETTINGS
#
# title of site appears in banner
title: 电白年例一览 An Overview of Dianbai Nianli
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: 体验近几年电白年例的多彩文化盛宴 Experience the Colorful Cultural Feast of Dianbai Nianli in Recent Years
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: 本网站聚焦于电白19个镇及4个街道的年例习俗，致力于全方位展示其独特魅力。在筹备过程中，虽因信息收集和照片使用授权问题，部分地区的资料尚未完善，但基于已收集到的信息，我们发现电白年例蕴含诸多有趣特点，值得深入探究。

This website is dedicated to showcasing the unique customs of the Nianli Festival across 19 towns and 4 sub-districts in Dianbai. Despite challenges in information collection and photo authorization, which have left some regions with incomplete data, the gathered information reveals many fascinating aspects of the Dianbai Nianli Festival, making it a subject worthy of in-depth exploration.
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: 梁晓蕾

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection 
# This will be the full URL to your CSV file or relative path + filename of CSV in this repository 
# e.g. relative path "/assets/demo-metadata.csv"
# e.g. published google sheet "https://docs.google.com/spreadsheets/d/e/2PACX-1vSn7AA-cbsXT3_nNUGftc1ab-CKXOJHMQCIENeR9NHElbyI9_qA99o0-HNZdG04v-M2_N21bUe_krQQ/pub?output=csv"
# e.g. on GitHub use the raw link "https://raw.githubusercontent.com/CollectionBuilder/collectionbuilder-sample-data/main/psychiana_cbdemo_gh.csv"
metadata-csv: https://docs.google.com/spreadsheets/d/e/2PACX-1vSCAqsk47PCtHduy2cAAvQy_WAQY_RE1gbmLZFdIICFucJ7ousPR7rH0sbMzXbLbyO9ehPB8hzMUkps/pub?output=csv

##########
# Site/Organization Branding 
# 
# Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# dev mode turns on ability to change metadata
development-mode: true
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
